### ISSUE TITLE
Add documentation for non JS users

### ISSUE THREAD

**Issue by nkh** [ozh/ascii-tables#22]
Hi, I'd like to integrate your module in the next version of asciio.

Could you write down how to install the needed environment and how to generate bales from the command line?

I can manage that of course but I think it  would be a good addition for other non JS developers that like what you are doing and want to use it.

**Comment by ozh** [comment]
Sorry I don't know asciio or what you need to add something in that stuff

**Comment by nkh** [comment]
https://www.youtube.com/watch?v=0l9W84PhOyI

It draws ASCII drawing in a graphical interface (although next version will also have a curses interface). Tables are sometimes needed by the users. I find your application interesting and would like to integrate it. it would be called as an external command to generate the rendering. 

I quickly looked at the repo and I saw an example of how to add it to a web page. I am no JS developer (yet!) so if there were instruction on how to install it, whatever dependencies it has, how to call it from the command line, what error codes it can return, ... that would be a great help, and my guess is that it would help other potential users.
