### ISSUE TITLE
Feature suggestion: Monospace

### ISSUE THREAD

**Issue by ryancwalsh** [ozh/ascii-tables#26]
Your ascii-tables tool is SO AWESOME!

I've never seen anything quite like it.  I love it.

I don't know whether this would be interesting to you, but a feature that I'd personally love and would use would be the ability to output a monospaced table that would look good when pasting into a Facebook post.

I've been trying to use your tool plus sites like http://slothsoft.net/UnicodeMapper/?lang=en-us and http://qaz.wtf/u/convert.cgi but haven't quite figured it out yet. 

It looks like the hyphens and spaces lose their monospacing.

But I bet it's possible.

Any ideas?

**Comment by ozh** [comment]
You can play with [unicode fullwidth chars](http://www.linkstrasse.de/en/%EF%BD%86%EF%BD%95%EF%BD%8C%EF%BD%8C%EF%BD%97%EF%BD%89%EF%BD%84%EF%BD%94%EF%BD%88%EF%BC%8D%EF%BD%83%EF%BD%8F%EF%BD%8E%EF%BD%96%EF%BD%85%EF%BD%92%EF%BD%94%EF%BD%85%EF%BD%92) but the thing is, the formatting in the post textarea form and the formatting once saved has nothing in common.

I don't think this is feasible.
