### ISSUE TITLE
Feature Request: change input format

### ISSUE THREAD

**Issue by styfle** [ozh/ascii-tables#33]
I like that you can change the output format to any number of tables but I would like to convert one table to another using this tool.

I think that an *Input Style* dropdown would be perfect.

### Artist's rendition

![input style](https://user-images.githubusercontent.com/229881/39529451-b3f1eca0-4df4-11e8-8db3-f8cbd78d70de.png)

**Comment by ozh** [comment]
Pull Request welcome! :)
