### ISSUE TITLE
Idea: line prefix

### ISSUE THREAD

**Issue by thejohnfreeman** [ozh/ascii-tables#35]
To make it easy to generate comments, even indented, offer an input for a prefix that appears on every line, e.g. "`⎵⎵⎵⎵#⎵`" would be a four-space indented Python comment.

**Comment by ozh** [comment]
Honestly I feel this would fix a problem that doesnt exist. Way easier to handle proper indentation as needed within your text/code editor (eg select a whole paragraph, hit Tab, every line is four space indented, right?)

**Comment by thejohnfreeman** [comment]
Unless I'm pasting into a webpage or a notebook where I don't have a smart editor, but that's fine.

**Comment by dwesely** [comment]
I found myself looking for the same feature, didn't notice it was reported as an issue until after I committed the update. I had added the prefix option into the branch I made the pull request for earlier today, #36 . My thought was to use it when posting to a webpage or if I'm not using my usual IDE or  something.
