### ISSUE TITLE
Comment style: Javadoc

### ISSUE THREAD

**Issue by viliam-durina** [ozh/ascii-tables#38]
Would be nice to add Javadoc comment style: prefix with `"* "`:

```
/**
 * +---------+---------+------+
 * |  Col1   |  Col2   | Col3 |
 * +---------+---------+------+
 * | Value 1 | Value 2 |  123 |
 * | Value 3 | Value 4 |  789 |
 * +---------+---------+------+
 */

**Comment by ozh** [comment]
Pull request welcome! Maybe @dwesely can help you on this :)

**Comment by ozh** [comment]
(note that the name should be "docblock" rather than "javadoc", since "phpdoc" has the same syntax)

**Comment by j-f1** [comment]
And JSDoc!

**Comment by ozh** [comment]
It's been added FYI
