### ISSUE TITLE
Reddit : add Pipe "|"  to comment style drop-down.

### ISSUE THREAD

**Issue by thurstonzd** [ozh/ascii-tables#50]
To better support tables in Reddit-style markdown, it would be ideal to allow a table to begin and end with a pipe character. As noted in [Reddit's Markdown Guide](https://www.reddit.com/wiki/markdown#wiki_tables):

>  Tip: Tables can be written without the row-leading and -ending pipe (|) characters, but the result can be surprising when the parser has to guess whether the row is a table row or something else. Leading and trailing pipes make it explicit you are writing a table.

While a more "correct" method might be to add an option to the __Output Style__ drop-down, I think an easier fix would be to use the __Comment Style__ drop-down:

 - Add `<option value="pipe">"|" Pipe</option>` to the `#commenting` select element.
 - Add the following `case` statement in `script.js`:

```
    case "pipe":
        prefix = "|";
        suffix = "|";
        break;
```

I've confirmed this creates valid tables in Reddit posts.

**Comment by ozh** [comment]
Fancy a pull request? :)
