### ISSUE TITLE
Library on NPM

### ISSUE THREAD

**Issue by jcubic** [ozh/ascii-tables#52]
This is nice library did you though about creating it as JavaScript library with nice API so you can actually write tables in browser and Node.js.

Is this Open Source? Maybe you should pick a license like MIT or it's All right reserved?

I can help with creating a library with your code if you need help.

**Comment by jcubic** [comment]
It seems duplicate of #34

**Comment by ozh** [comment]
I have no interest in NPM (I have very little interest in JS to be honest :)

License added in the readme
